### PR TITLE
Added a simple build script and new ids in the template

### PR DESCRIPTION
**Pull request by hemanth**
Now, `bjs` must be able to parse easily ;)  Yet to check on the redirection part.

### CODE REVIEW

**Comment by hemanth** [comment]
@jonmaim meow :)?

**Comment by jonmaim** [comment]
@hemanth where is `build.sh`?

**Comment by hemanth** [comment]
@jonmaim ^ There :smile:

**Comment by hemanth** [comment]
:+1:

On Mon, Jan 13, 2014 at 11:25 AM, Jon Maim notifications@github.com wrote:

> Merged #4 https://github.com/minsh/sambar/pull/4.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minsh/sambar/pull/4
> .

## 

_'I am what I am because of who we all are'_
h3manth.com http://www.h3manth.com
*-- Hemanth HM *

**Comment by jonmaim** [comment]
thanks man for the PR and sorry for the delay!

Coming for the next meetup in Jan 25th?

**Comment by hemanth** [comment]
NP! Undoubtedly I'll be there :smile:

**Comment by jonmaim** [comment]
\o/

Jon

**Pull request merged**
